### PR TITLE
Fix 188/revisit lifetimes

### LINKED ISSUE #188: Change `NodeRef::walk_with` to not require `traverser` to live as long as the tree / node
Currently, `NodeRef::walk_with` is defined as `<'t>(&'t self, traverser: &'t mut T)`, meaning the `traverser` has to live as long as the node itself, meaing the following is not possible with `walk_with`, but is possible with `walk`:

```rust
fn find_node<'a>(tree: &Tree<Data>, predicate: &str) -> Option<Node<'a, Data>> {
    let root_node = tree.get_root()?;

    let mut traverser = Dfs::<OverNode>::new();
    let mut walker = root_node.walk_with(&mut traverser);

    let node = walker.find(|v| v.data().something == predicate);

    // ERROR: cannot return value referencing local variable `traverser`
    node
}
```

I have already tried changing the NodeRef signature to the following, which seemingly fixes it, but it requires cascading changes to `TraverserCore` and all things that implement it:
```rust
    fn walk_with<'t, T, O>(
        &'a self,
        traverser: &'t mut T,
    ) -> impl Iterator<Item = OverItem<'a, V, O, M, P>> + 't
    where
        O: Over,
        T: Traverser<O>,
        Self: Sized,
        'a: 't
    {
        traverser.iter(self)
    }
```

---

The current workaround is to use `Node::clone` as it is still a cheap clone (pointer only clone), though still a weird error in that place.

### PR DESCRIPTION
**Pull request by orxfun**
Lifetimes of `self` references of `NodeRef` and `NodeMut` methods are revised.

Tests are added to make sure that expected code blocks compile: https://github.com/orxfun/orx-tree/blob/fix-188/revisit-lifetimes/tests/iterator_lifetimes.rs.

The fixes mostly break the dependency of the node reference and an iterator created from the node reference. Instead, the returned values lifetime is bound to the lifetime of the tree. Similar fixes are made for lifetime dependencies to the traversers.

Fixes #188

### CODE REVIEW

File: src/dary/variant.rs [hunk 1]
```diff
@@ -8,6 +8,12 @@ pub struct Dary<const D: usize, T> {
     p: PhantomData<T>,
 }
 
+/// Tree variants do not hold any data; and hence, safe to sync.
+unsafe impl<const D: usize, T> Sync for Dary<D, T> {}
+
+/// Tree variants do not hold any data; and hence, safe to sync.
+unsafe impl<const D: usize, T> Send for Dary<D, T> {}
```
Comment (hasezoey) [inline src/dary/variant.rs]: Might wanna make the documentation consistently either include or exclude having a `# Safety` header

File: tests/iterator_lifetimes.rs [hunk 2]
```diff
@@ -0,0 +1,338 @@
+use orx_tree::traversal::*;
+use orx_tree::*;
+
+/*
+These tests are created wrt the issue: https://github.com/orxfun/orx-tree/issues/188.
```
Comment (hasezoey) [inline tests/iterator_lifetimes.rs]: Is `wrt` a typo, or what does it mean?

File: src/node_ref.rs [hunk 3]
```diff
@@ -1758,16 +1782,18 @@ where
     ///     .collect();
     /// assert_eq!(bfs_leaves, [5, 8, 9, 10, 11]);
     /// ```
-    fn leaves<T>(&'a self) -> impl Iterator<Item = &'a V::Item>
+    fn leaves<'t, T>(&self) -> impl Iterator<Item = &'a V::Item> + 't
     where
-        T: Traverser<OverData>,
+        T: Traverser<OverData> + 't,
+        <T as TraverserCore>::Storage<V>: 't,
```
Comment (hasezoey) [inline src/node_ref.rs]: Couldnt this line be omitted as (to my knowledge) it is already inherited by the above `T: /*...*/ + 't`?

File: src/node_ref.rs [hunk 4]
```diff
@@ -1979,10 +2006,11 @@ where
     /// assert_eq!(a.node(dfs_indices[2]).data(), &3);
     /// assert_eq!(a.node(dfs_indices[3]).data(), &7);
     /// ```
-    fn indices<T>(&self) -> impl Iterator<Item = NodeIdx<V>>
+    fn indices<'t, T>(&self) -> impl Iterator<Item = NodeIdx<V>> + 't
     where
-        T: Traverser<OverData>,
-        V: 'static,
+        T: Traverser<OverData> + 't,
+        <T as TraverserCore>::Storage<V>: 't,
```
Comment (hasezoey) [inline src/node_ref.rs]: Couldnt this line be omitted as (to my knowledge) it is already inherited by the above `T: /*...*/ + 't`?

File: src/traversal/traverser_core.rs [hunk 5]
```diff
@@ -212,35 +219,40 @@ where
...
+        'a: 't,
     {
         Self::iter_with_storage(node, Self::Storage::default())
     }
 
-    fn iter_mut_with_owned_storage<'a, V, M, P, MO>(
-        node_mut: &'a mut NodeMut<'a, V, M, P, MO>,
-    ) -> impl Iterator<Item = OverItemMut<'a, V, O, M, P>>
+    fn iter_mut_with_owned_storage<'t, 'a, V, M, P, MO>(
+        node_mut: &mut NodeMut<'a, V, M, P, MO>,
```
Comment (hasezoey) [inline src/traversal/traverser_core.rs]:
```suggestion
        node: &mut NodeMut<'a, V, M, P, MO>,
```

The other functions practically all use `node`, so might be worth to change it here too to be consistent.

**Review by hasezoey — APPROVED** [review]
Looks great, just some style nitpicks.

File: tests/iterator_lifetimes.rs (hunk 2 above)
Comment (orxfun) [reply tests/iterator_lifetimes.rs]: with respect to:) an old habit, changing to open version.

File: tests/iterator_lifetimes.rs [hunk 6]
```diff
@@ -0,0 +1,338 @@
...
+fn find_custom_walk<'a, V: TreeVariant>(
+    tree: &'a Tree<V>,
+    predicate: &V::Item,
+) -> Option<&'a V::Item>
+where
+    V::Item: Eq + Sync + Send,
+{
+    let custom_walk = |node: Node<'a, V>| node.get_child(0);
+    let root = tree.get_root()?;
+    let mut walker = root.custom_walk(custom_walk);
```
[the remark this answers is not in the document]
Comment (orxfun) [reply tests/iterator_lifetimes.rs]: Yes, certainly.

File: src/node_mut.rs [hunk 7]
```diff
@@ -2048,9 +2052,8 @@ where
     /// ```
     pub fn children_mut(
         &mut self,
-    ) -> impl ExactSizeIterator<Item = NodeMut<'_, V, M, P, NodeMutDown>>
-    + DoubleEndedIterator
-    + use<'_, 'a, V, M, P, MO> {
+    ) -> impl ExactSizeIterator<Item = NodeMut<'_, V, M, P, NodeMutDown>> + DoubleEndedIterator
```
[the remark this answers is not in the document]
Comment (orxfun) [reply src/node_mut.rs]: That's true.
